<a href="https://colab.research.google.com/github/bksgupta/course-v3/blob/master/lesson7_human_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Human numbers

In [62]:
from fastai.text import *

In [63]:
bs=64

## Data

In [64]:
path = untar_data(URLs.HUMAN_NUMBERS)
path.ls()

[PosixPath('/root/.fastai/data/human_numbers/valid.txt'),
 PosixPath('/root/.fastai/data/human_numbers/train.txt')]

In [65]:
path

PosixPath('/root/.fastai/data/human_numbers')

In [66]:
!cat {path}/'train.txt'

one 
two 
three 
four 
five 
six 
seven 
eight 
nine 
ten 
eleven 
twelve 
thirteen 
fourteen 
fifteen 
sixteen 
seventeen 
eighteen 
nineteen 
twenty 
twenty one 
twenty two 
twenty three 
twenty four 
twenty five 
twenty six 
twenty seven 
twenty eight 
twenty nine 
thirty 
thirty one 
thirty two 
thirty three 
thirty four 
thirty five 
thirty six 
thirty seven 
thirty eight 
thirty nine 
forty 
forty one 
forty two 
forty three 
forty four 
forty five 
forty six 
forty seven 
forty eight 
forty nine 
fifty 
fifty one 
fifty two 
fifty three 
fifty four 
fifty five 
fifty six 
fifty seven 
fifty eight 
fifty nine 
sixty 
sixty one 
sixty two 
sixty three 
sixty four 
sixty five 
sixty six 
sixty seven 
sixty eight 
sixty nine 
seventy 
seventy one 
seventy two 
seventy three 
seventy four 
seventy five 
seventy six 
seventy seven 
seventy eight 
seventy nine 
eighty 
eighty one 
eighty two 
eighty three 
eighty four 
eighty five 
eighty six 
eighty seven 
eighty eight 
eighty nine 
n

In [67]:
# strip does away with the newlines
def readnums(d): return [', '.join(o.strip() for o in open(path/d).readlines())]

In [68]:
train_txt = readnums('train.txt'); train_txt[0][:80]

'one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirt'

In [69]:
train_txt = readnums('train.txt'); train_txt[0][:80]

'one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirt'

In [70]:
valid_txt = readnums('valid.txt'); valid_txt[0][-80:]

' nine thousand nine hundred ninety eight, nine thousand nine hundred ninety nine'

In [71]:
train = TextList(train_txt, path=path)
valid = TextList(valid_txt, path=path)

src = ItemLists(path=path, train=train, valid=valid).label_for_lm()
data = src.databunch(bs=bs)

In [72]:
train[0].text[:80]

'xxbos one , two , three , four , five , six , seven , eight , nine , ten , eleve'

In [75]:
len(data.valid_ds[0][0].data)

13017

In [76]:
len(data.train_ds[0][0].data)

50079

In [77]:
50079/70/bs

11.178348214285714

In [78]:
data.bptt, len(data.valid_dl), len(data.train_dl)

(70, 3, 12)

In [79]:
13017/70/bs

2.905580357142857

In [80]:
it = iter(data.valid_dl)
x1,y1 = next(it)
x2,y2 = next(it)
x3,y3 = next(it)
it.close()

In [81]:
x1.numel()

4480

In [82]:
x1.numel()+x2.numel()+x3.numel()

13440

In [83]:
x1.shape,y1.shape

(torch.Size([64, 70]), torch.Size([64, 70]))

In [84]:
x2.shape,y2.shape

(torch.Size([64, 70]), torch.Size([64, 70]))

In [85]:
x1[:,0]

tensor([ 2,  9, 11, 12, 13, 11, 10,  9, 10, 14, 19, 25, 19, 15, 16, 11, 19,  9,
        10,  9, 19, 25, 19, 11, 19, 11, 10,  9, 19, 20, 11, 26, 20, 23, 20, 20,
        24, 20, 11, 14, 11, 11,  9, 14,  9, 20, 10, 20, 35, 17, 11, 10,  9, 17,
         9, 20, 10, 20, 11, 20, 11, 20, 20, 20], device='cuda:0')

In [86]:
x1[:,69].size()

torch.Size([64])

In [87]:
x1[63].size()

torch.Size([70])

In [88]:
y1[:,0]

tensor([19, 19, 27, 10,  9, 12, 32, 19, 26, 10, 11, 15, 11, 10,  9, 15, 11, 19,
        26, 19, 11, 18, 11, 18,  9, 18, 21, 19, 10, 10, 20,  9, 11, 16, 11, 11,
        13, 11, 13,  9, 13, 14, 20, 10, 20, 11, 24, 11,  9,  9, 16, 17, 20, 10,
        20, 11, 24, 11, 19,  9, 19, 11, 11, 10], device='cuda:0')

In [89]:
data.valid_ds.vocab

In [90]:
v = data.valid_ds.vocab

In [91]:
v.textify(x1[0])

'xxbos eight thousand one , eight thousand two , eight thousand three , eight thousand four , eight thousand five , eight thousand six , eight thousand seven , eight thousand eight , eight thousand nine , eight thousand ten , eight thousand eleven , eight thousand twelve , eight thousand thirteen , eight thousand fourteen , eight thousand fifteen , eight thousand sixteen , eight thousand seventeen , eight'

In [92]:
v.textify(y1[0])

'eight thousand one , eight thousand two , eight thousand three , eight thousand four , eight thousand five , eight thousand six , eight thousand seven , eight thousand eight , eight thousand nine , eight thousand ten , eight thousand eleven , eight thousand twelve , eight thousand thirteen , eight thousand fourteen , eight thousand fifteen , eight thousand sixteen , eight thousand seventeen , eight thousand'

In [93]:
v.textify(x2[0])

'thousand eighteen , eight thousand nineteen , eight thousand twenty , eight thousand twenty one , eight thousand twenty two , eight thousand twenty three , eight thousand twenty four , eight thousand twenty five , eight thousand twenty six , eight thousand twenty seven , eight thousand twenty eight , eight thousand twenty nine , eight thousand thirty , eight thousand thirty one , eight thousand thirty two ,'

In [94]:
v.textify(x3[0])

'eight thousand thirty three , eight thousand thirty four , eight thousand thirty five , eight thousand thirty six , eight thousand thirty seven , eight thousand thirty eight , eight thousand thirty nine , eight thousand forty , eight thousand forty one , eight thousand forty two , eight thousand forty three , eight thousand forty four , eight thousand forty five , eight thousand forty six , eight'

In [95]:
v.textify(x1[1])

', eight thousand forty six , eight thousand forty seven , eight thousand forty eight , eight thousand forty nine , eight thousand fifty , eight thousand fifty one , eight thousand fifty two , eight thousand fifty three , eight thousand fifty four , eight thousand fifty five , eight thousand fifty six , eight thousand fifty seven , eight thousand fifty eight , eight thousand fifty nine ,'

In [96]:
v.textify(x2[1])

'eight thousand sixty , eight thousand sixty one , eight thousand sixty two , eight thousand sixty three , eight thousand sixty four , eight thousand sixty five , eight thousand sixty six , eight thousand sixty seven , eight thousand sixty eight , eight thousand sixty nine , eight thousand seventy , eight thousand seventy one , eight thousand seventy two , eight thousand seventy three , eight thousand'

In [97]:
v.textify(x3[1])

'seventy four , eight thousand seventy five , eight thousand seventy six , eight thousand seventy seven , eight thousand seventy eight , eight thousand seventy nine , eight thousand eighty , eight thousand eighty one , eight thousand eighty two , eight thousand eighty three , eight thousand eighty four , eight thousand eighty five , eight thousand eighty six , eight thousand eighty seven , eight thousand eighty'

In [98]:
v.textify(x3[-1])

'ninety , nine thousand nine hundred ninety one , nine thousand nine hundred ninety two , nine thousand nine hundred ninety three , nine thousand nine hundred ninety four , nine thousand nine hundred ninety five , nine thousand nine hundred ninety six , nine thousand nine hundred ninety seven , nine thousand nine hundred ninety eight , nine thousand nine hundred ninety nine xxbos eight thousand one , eight'

In [99]:
data.show_batch(ds_type=DatasetType.Valid)

## Single fully connected model

In [100]:
data = src.databunch(bs=bs, bptt=3)

In [101]:
bs

64

In [102]:
data.bptt

3

In [103]:
x,y = data.one_batch()
x.shape,y.shape

(torch.Size([64, 3]), torch.Size([64, 3]))

In [104]:
v.textify(x[1]), x.shape

('two hundred eleven', torch.Size([64, 3]))

In [105]:
v.textify(y[1])

'hundred eleven ,'

In [106]:
x[1].shape

torch.Size([3])

In [107]:
y[1].shape

torch.Size([3])

In [108]:
v.textify(y[:,-1])

', , , forty , seventy , seventy one thousand six one one eight hundred one hundred one seven four , two thousand one three hundred fifty seven , three eighteen forty thousand two hundred hundred forty three , four five five three hundred five hundred three nine , , six thousand hundred hundred hundred twenty seven , three , thousand six hundred eighty'

In [109]:
y[:,-1].shape

torch.Size([64])

In [110]:
v.itos

['xxunk',
 'xxpad',
 'xxbos',
 'xxeos',
 'xxfld',
 'xxmaj',
 'xxup',
 'xxrep',
 'xxwrep',
 ',',
 'hundred',
 'thousand',
 'one',
 'two',
 'three',
 'four',
 'five',
 'six',
 'seven',
 'eight',
 'nine',
 'twenty',
 'thirty',
 'forty',
 'fifty',
 'sixty',
 'seventy',
 'eighty',
 'ninety',
 'ten',
 'eleven',
 'twelve',
 'thirteen',
 'fourteen',
 'fifteen',
 'sixteen',
 'seventeen',
 'eighteen',
 'nineteen',
 'xxfake']

In [111]:
nv = len(v.itos); nv

40

In [112]:
nh=64

In [113]:
def loss4(input,target): 
  # print('inside loss ', input.shape,target.shape,target[:,-1].shape)
  return F.cross_entropy(input, target[:,-1])
def acc4 (input,target): return accuracy(input, target[:,-1])

In [114]:
class Model0(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)  # green arrow
        self.h_h = nn.Linear(nh,nh)     # brown arrow
        self.h_o = nn.Linear(nh,nv)     # blue arrow
        self.bn = nn.BatchNorm1d(nh)
        
    def forward(self, x):
        # print('x shape',x.shape )    
        h = self.bn(F.relu(self.h_h(self.i_h(x[:,0]))))
        if x.shape[1]>1:
            h = h + self.i_h(x[:,1])
            h = self.bn(F.relu(self.h_h(h)))
        if x.shape[1]>2:
            h = h + self.i_h(x[:,2])
            h = self.bn(F.relu(self.h_h(h)))
        # print('ou6tplu6t shape',self.h_o(h).shape )    
        return self.h_o(h)

In [115]:
learn = Learner(data, Model0(), loss_func=loss4, metrics=acc4)

In [116]:
learn.fit_one_cycle(6, 1e-4)

## Same thing with a loop

In [117]:
x[:,1].shape

torch.Size([64])

In [118]:
class Model1(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)  # green arrow
        self.h_h = nn.Linear(nh,nh)     # brown arrow
        self.h_o = nn.Linear(nh,nv)     # blue arrow
        self.bn = nn.BatchNorm1d(nh)
        
    def forward(self, x):
        h = torch.zeros(x.shape[0], nh).to(device=x.device)
        for i in range(x.shape[1]):
            h = h + self.i_h(x[:,i])
            h = self.bn(F.relu(self.h_h(h)))
            # print (F.relu(self.h_h(h)).shape)
        return self.h_o(h)

In [119]:
nn.BatchNorm1d??

In [120]:
##Some exploration on batchnorm
a = torch.rand((2,2,2,2))
print (a)
print ('------')
b = nn.BatchNorm2d(2)(a)
print (b.shape)
print (b)

tensor([[[[0.3444, 0.1922],
          [0.6146, 0.7474]],

         [[0.8208, 0.5238],
          [0.5786, 0.3119]]],


        [[[0.8222, 0.0173],
          [0.5531, 0.2197]],

         [[0.2461, 0.9988],
          [0.7951, 0.2768]]]])
------
torch.Size([2, 2, 2, 2])
tensor([[[[-0.3505, -0.9147],
          [ 0.6518,  1.1442]],

         [[ 0.9542, -0.1714],
          [ 0.0364, -0.9740]]],


        [[[ 1.4217, -1.5634],
          [ 0.4235, -0.8127]],

         [[-1.2235,  1.6286],
          [ 0.8568, -1.1071]]]], grad_fn=<NativeBatchNormBackward>)


In [121]:
learn = Learner(data, Model1(), loss_func=loss4, metrics=acc4)

In [122]:
learn.summary()

Model1
Layer (type)         Output Shape         Param #    Trainable 
Embedding            [64]                 2,560      True      
______________________________________________________________________
Linear               [64]                 4,160      True      
______________________________________________________________________
Linear               [40]                 2,600      True      
______________________________________________________________________
BatchNorm1d          [64]                 128        True      
______________________________________________________________________

Total params: 9,448
Total trainable params: 9,448
Total non-trainable params: 0
Optimized with 'torch.optim.adam.Adam', betas=(0.9, 0.99)
Using true weight decay as discussed in https://www.fast.ai/2018/07/02/adam-weight-decay/ 
Loss function : function
Callbacks functions applied 

In [123]:
learn.fit_one_cycle(6, 1e-4)

## Multi fully connected model

In [124]:
data = src.databunch(bs=bs, bptt=20)

In [125]:
x,y = data.one_batch()
x.shape,y.shape
x.device

device(type='cpu')

In [126]:
class Model2(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)
        self.h_h = nn.Linear(nh,nh)
        self.h_o = nn.Linear(nh,nv)
        self.bn = nn.BatchNorm1d(nh)
        
    def forward(self, x):
        h = torch.zeros(x.shape[0], nh).to(device=x.device)
        res = []
        for i in range(x.shape[1]):
            h = h + self.i_h(x[:,i])
            h = F.relu(self.h_h(h))
            res.append(self.h_o(self.bn(h)))
        # print (res[0].shape)
        # print (torch.stack(res, dim=1).shape)
        return torch.stack(res, dim=1)

In [127]:
learn = Learner(data, Model2(), metrics=accuracy)

In [128]:
data.train_dl.dl.dataset.loss_func

FlattenedLoss of CrossEntropyLoss()

In [129]:
??Learner

In [ ]:
??accuracy

In [130]:
learn.fit_one_cycle(10, 1e-4, pct_start=0.1)

## Maintain state

In [131]:
class Model3(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)
        self.h_h = nn.Linear(nh,nh)
        self.h_o = nn.Linear(nh,nv)
        self.bn = nn.BatchNorm1d(nh)
        self.h = torch.zeros(bs, nh).cuda()
        
    def forward(self, x):
        res = []
        h = self.h
        for i in range(x.shape[1]):
            h = h + self.i_h(x[:,i])
            h = F.relu(self.h_h(h))
            res.append(self.bn(h))
        self.h = h.detach()
        # print (h)
        # self.h = h
        res = torch.stack(res, dim=1)
        res = self.h_o(res)
        return res

In [132]:
learn = Learner(data, Model3(), metrics=accuracy)

In [133]:
learn.fit_one_cycle(20, 3e-3)

## nn.RNN

In [134]:
class Model4(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)
        self.rnn = nn.RNN(nh,nh, batch_first=True)
        self.h_o = nn.Linear(nh,nv)
        self.bn = BatchNorm1dFlat(nh)
        self.h = torch.zeros(1, bs, nh).cuda()
        
    def forward(self, x):
        res,h = self.rnn(self.i_h(x), self.h)
        # print (res.shape,h.shape,self.bn(res).shape,self.i_h(x).shape)
        self.h = h.detach()
        # print (self.h_o(self.bn(res)).shape)
        return self.h_o(self.bn(res))

In [131]:
??nn.RNN

In [57]:
x.shape

torch.Size([64, 20])

In [136]:
rnn = nn.RNN(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)

output.shape,hn.shape

(torch.Size([5, 3, 20]), torch.Size([2, 3, 20]))

In [137]:
learn = Learner(data, Model4(), metrics=accuracy)

In [127]:
??BatchNorm1dFlat

In [59]:
a = torch.rand(64, 20, 64)
*f,l = a.shape

In [60]:
a.shape

torch.Size([64, 20, 64])

In [129]:
f

[64, 20]

In [130]:
l

64

In [138]:
learn.fit_one_cycle(20, 3e-3)

## 2-layer GRU

In [139]:
class Model5(nn.Module):
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv,nh)
        self.rnn = nn.GRU(nh, nh, 2, batch_first=True)
        self.h_o = nn.Linear(nh,nv)
        self.bn = BatchNorm1dFlat(nh)
        self.h = torch.zeros(2, bs, nh).cuda()
        
    def forward(self, x):
        res,h = self.rnn(self.i_h(x), self.h)
        self.h = h.detach()
        return self.h_o(self.bn(res))

In [140]:
learn = Learner(data, Model5(), metrics=accuracy)

In [141]:
learn.fit_one_cycle(10, 1e-2)

## fin